### ISSUE TITLE
3 papers I proposed

### ISSUE THREAD

**Issue by ErbB4** [reading-club/reading-club.github.io#3]
Hi guys,
Here are the papers I proposed to present in our ANN-CompNeu Reading Club.
1. Is cortical network optimized for storing information? a close look at recurrent network in the brain.
   [nn.4286.pdf](https://github.com/reading-club/reading-club.github.io/files/524683/nn.4286.pdf)
2. redundant network hypothesis for information representation in primary motor cortex.
   [2007-Motor_learning_with_unstable_neural_representations..pdf](https://github.com/reading-club/reading-club.github.io/files/524684/2007-Motor_learning_with_unstable_neural_representations.pdf)
3. Tempotron hypothesis (temporal-spatial coding) for information encoding in primary sensory cortex.
   [nn1643.pdf](https://github.com/reading-club/reading-club.github.io/files/524682/nn1643.pdf)

**Comment by emptymalei** [comment]
我提议的：
1. [Papadopoulos et al. - 2012 - Popularity versus similarity in growing networks(2).pdf](https://github.com/reading-club/reading-club.github.io/files/527707/Papadopoulos.et.al.-.2012.-.Popularity.versus.similarity.in.growing.networks.2.pdf)  
   (Supplementary Information: [Papadopoulos et al. - 2012 - Popularity versus similarity in growing networks.pdf](https://github.com/reading-club/reading-club.github.io/files/527706/Papadopoulos.et.al.-.2012.-.Popularity.versus.similarity.in.growing.networks.pdf) ): This paper talks about two significant factors of a network, and introduces the concept of similarity by mapping a network onto hyperbolic geometry.
2. [Watts, Strogatz - 1998 - Collective dynamics of 'small-world' networks.pdf](https://github.com/reading-club/reading-club.github.io/files/527709/Watts.Strogatz.-.1998.-.Collective.dynamics.of.small-world.networks.pdf): A paper about how small world network can have emergent phenomenon.
3. [Cremers, Herz - 2002 - Traveling waves of excitation in neural field models equivalence of rate descriptions and integrate-and-fire dyna.pdf](https://github.com/reading-club/reading-club.github.io/files/527716/Cremers.Herz.-.2002.-.Traveling.waves.of.excitation.in.neural.field.models.equivalence.of.rate.descriptions.and.integrate-and-fire.dyna.pdf): traveling waves in neural networks. This is important because traveling waves means we have enhanced signal propagation in the network without very much damping.

**Comment by skyworlds** [comment]
3 papers:
1.  [2004-Computing the meanings of words in reading cooperative division of labor between visual and phonological processes](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.14.4088&rep=rep1&type=pdf) : This paper is the first one investigating interactions between phonological, orthographic, and semantic representations in a neural network in order to explain human reading development. Although the model seems too simple and quite weak, it inspires intensive discussion and debates in reading research.
2. [2001-DRC A Dual Route Cascaded model of visual word recognition and reading aloud](http://psiexp.ss.uci.edu/research/teachingP140C/Papers/Coltheart_etal_2001.pdf) : A powerful competitor to the triangle model of reading. It is argued that the idea of rule-based symbolism is enough to explain cognitive processing of reading and the philosophy of connectionism behind neural networks is wrong.
3. [2010-Beyond single syllables Large-scale modeling of reading aloud with the Connectionist Dual Process (CDP++) model](http://147.94.113.25/gsite/Local/lpc/dir/ziegler/article/Perry_Cog_Psy_2010.pdf) : This model deemphasizes theoretical disputes and integrates the triangle model of reading and DRC.

**Comment by liuyuue** [comment]
1. http://www.pnas.org/content/110/31/12828.full.pdf?with-ds=yes
   --- A network model that can function as working memory under oscillatory inputs.
2. http://ruccs.rutgers.edu/images/personal-zenon-pylyshyn/proseminars/Proseminar13/ConnectionistArchitecture.pdf
   --- A critique about what connectionist networks cannot do. 
3. https://www.ncbi.nlm.nih.gov/pubmed/23177967
   --- An experimental paper about the role of brain oscillation in rule learning tasks for monkey.

**Comment by davidz-zzz** [comment]
1. [http://arxiv.org/abs/1312.5602](http://arxiv.org/abs/1312.5602) --- Playing Atari with Deep Reinforcement Learning
2. [http://arxiv.org/abs/1604.04573#](http://arxiv.org/abs/1604.04573#) --- CNN-RNN: A Unified Framework for Multi-label Image Classification
3. [https://arxiv.org/pdf/1609.03499v2.pdf](https://arxiv.org/pdf/1609.03499v2.pdf) --- WaveNet: A Generative Model for Raw Audio

**Comment by ErbB4** [comment]
currently voted papers:
ErbB4: 1, 1, 1, 2, 1
emptymalei: 1, 2, 3, 1
skyworlds: 1, 1, 2, 3
coldlikebrain: 1, 2, 1, 1, 2, 1
zlslhp: 1, 2, 1

**Comment by ruyuanzhang** [comment]
Dear all.
I am interested in mechanisms of sensory processing and perceptual decision-making, especially in visual domain. Here are the papers I suggest:
1. http://www.cell.com/neuron/pdf/S0896-6273(16)30639-0.pdf. Neural Variability and Sampling-Based Probabilistic Representations in the Visual Cortex
2. http://www.nature.com/neuro/journal/v19/n3/abs/nn.4244.html. Using goal-driven deep learning models to understand sensory cortex
3. http://www.nature.com/neuro/journal/v17/n6/full/nn.3711.html.  Partitioning neuronal variability
